[package]
name = "scape-input"
version = "0.1.0"
edition = "2021"

[dependencies]
scape-shared = { path = "../scape-shared" }
anyhow = { workspace = true }
calloop = { workspace = true }
tracing = { workspace = true }
